### ISSUE TITLE
Settings of  MN and CN

### ISSUE THREAD

**Issue by MiraHyc** [dmemsys/SMART#20]
I want to change the settings of my MN and CN because there are not  so many CPU cores on my machine. I wonder where the default setting of MN and CN is defined in the code。

**Comment by River861** [comment]
By default, only 1 CPU core is used by each MN. We bind the last CPU core to the MN:
https://github.com/dmemsys/SMART/blob/1274148c849af987eb7e9815da007af8403d4155/src/Directory.cpp#L30-L32
Thus, you should set a appropriate `CPU_PHYSICAL_CORE_NUM` value:
https://github.com/dmemsys/SMART/blob/1274148c849af987eb7e9815da007af8403d4155/include/Common.h#L23


The number of CPU core used by each CN is determined by the number of clients you launch on each CN. This is because we bind a CPU core to each client:
https://github.com/dmemsys/SMART/blob/1274148c849af987eb7e9815da007af8403d4155/test/ycsb_test.cpp#L206-L207 
Thus, just reduce the number of clients you launch on each CN if there are not so many CPU cores on your machine.
